Repository The-Timeless-Tutor/v2-frontend, pull requests merged in 2024-04, with the labels that each got.

#1 Initialized Vite Project for v2 by @13x54r
  .eslintrc.cjs
  .gitignore
  README.md
  index.html
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  vite.config.js
Labels: documentation, enhancement

#3 feature: documentation for the frontend codebase updated
  README.md
Labels: documentation, enhancement

#5 feature:initial project config shell script & project structure added
  .env.example
  .gitignore
  README.md
  package.json
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
Labels: documentation, enhancement

#2 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#9 Initial setup
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .prettierrc
  README.md
  index.html
  package.json
  public/vite.svg
  src/App.jsx
  src/main.jsx
  vite.config.js
Labels: documentation, enhancement

#7 Create LICENSE
  LICENSE
Labels: documentation, enhancement

#10 feature: initial setup
  .eslintrc.cjs
  .prettierrc
  README.md
  index.html
  package.json
  public/vite.svg
  src/App.jsx
  src/main.jsx
  vite.config.js
Labels: documentation, enhancement

#11 Docker setup and basic css reset
  Dockerfile
  index.html
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/site.webmanifest
  src/App.jsx
  src/index.css
  src/main.jsx
Labels: documentation, enhancement, set up

#12 Refactor dev
  .eslintignore
  .gitignore
  index.html
  package.json
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/site.webmanifest
  src/_mock/account.js
  src/_mock/blog.js
  src/_mock/products.js
  src/_mock/user.js
  src/components/chart/chart.js
  src/components/chart/index.js
  src/components/chart/use-chart.js
  src/components/color-utils/color-picker.jsx
  src/components/color-utils/color-preview.jsx
  src/components/iconify/iconify.jsx
  src/components/label/label.jsx
  src/components/label/styles.js
  src/components/logo/logo.jsx
  src/components/scrollbar/scrollbar.jsx
  src/components/scrollbar/styles.js
  src/components/svg-color/svg-color.jsx
  src/hooks/use-responsive.js
  src/hooks/use-scroll-to-top.js
  src/layouts/dashboard/common/account-popover.jsx
  src/layouts/dashboard/common/language-popover.jsx
  src/layouts/dashboard/common/notifications-popover.jsx
  src/layouts/dashboard/common/searchbar.jsx
  src/layouts/dashboard/config-layout.js
  src/layouts/dashboard/config-navigation.jsx
  src/layouts/dashboard/header.jsx
  src/layouts/dashboard/index.jsx
  src/layouts/dashboard/main.jsx
  src/layouts/dashboard/nav.jsx
  src/pages/app.jsx
  src/pages/blog.jsx
  src/pages/login.jsx
  src/pages/page-not-found.jsx
  src/pages/products.jsx
  src/pages/user.jsx
  src/routes/components/router-link.jsx
  src/routes/hooks/use-pathname.js
  src/routes/hooks/use-router.js
  src/routes/sections.jsx
  src/sections/blog/post-search.jsx
  src/sections/blog/post-sort.jsx
  src/sections/error/not-found-view.jsx
  src/sections/login/login-view.jsx
  src/sections/overview/view/app-view.jsx
  vite.config.js
Labels: documentation

#15 feat: Dev Preview
  index.html
  package.json
  postcss.config.js
  src/_mock/products.js
  src/components/evervault-card/evervault-card.jsx
  src/components/evervault-card/styles/style.css
  src/components/evervault-card/styles/style.css.map
  src/components/evervault-card/styles/style.scss
  src/contexts/AuthContext.js
  src/global.css
  src/middleware/apiMiddleware.js
  src/pages/register.jsx
  src/routes/sections.jsx
  src/sections/login/login-view.jsx
  src/sections/overview/app-news-update.jsx
  src/sections/overview/view/app-view.jsx
  src/sections/products/product-card.jsx
  src/sections/products/view/products-view.jsx
  src/sections/register/register-view.jsx
  src/sections/user/user-table-toolbar.jsx
  src/sections/user/view/user-view.jsx
  src/sections/web3/view/web3-view.jsx
  src/utils/authUtils.js
  tailwind.config.js
Labels: documentation, enhancement

#16 fix:build issue
  src/routes/sections.jsx
Labels: bug

#17 feat:glassomorphism added on import wallet.
  package.json
  src/components/evervault-card/evervault-card.jsx
  src/components/import-wallet/import-wallet.jsx
  src/components/import-wallet/index.js
  src/components/import-wallet/styles/style.css
  src/components/import-wallet/styles/style.css.map
  src/components/import-wallet/styles/style.scss
  src/middleware/apiMiddleware.js
  src/sections/web3/view/web3-view.jsx
  src/utils/authUtils.js
Labels: documentation, enhancement

#18 feat:swap dex designed added
  .env.example
  package.json
  src/components/import-wallet/import-wallet.jsx
  src/components/slider/index.jsx
  src/sections/error/not-found-view.jsx
  src/sections/web3/view/web3-view.jsx
Labels: documentation, enhancement
