Repository The-Timeless-Tutor/v2-frontend, pull requests merged in 2024-05, with the labels that each got.

#21 Refactor Login and Authentication, changed to Shadcn and tanstack-query
  components.json
  jsconfig.json
  package.json
  public/assets/ttt-logo.png
  public/assets/ttt-logo.svg
  src/app.jsx
  src/components/logo/logo.jsx
  src/components/ui/toast.jsx
  src/components/ui/toaster.jsx
  src/components/ui/use-toast.js
  src/contexts/AuthContext.js
  src/contexts/AuthContext.jsx
  src/global.css
  src/layouts/dashboard/common/account-popover.jsx
  src/layouts/dashboard/nav.jsx
  src/lib/utils.js
  src/middleware/apiMiddleware.js
  src/routes/private-routes.jsx
  src/routes/sections.jsx
  src/sections/login/apiAuth.js
  src/sections/login/login-view.jsx
  src/sections/login/useGetUser.js
  src/sections/login/useIsAuthenticated.js
  src/sections/login/useLogin.js
  src/utils/constant.js
  tailwind.config.js
  vite.config.js
Labels: documentation, enhancement

#22 Add forgot password feature
  src/app.jsx
  src/pages/forgot-password.jsx
  src/pages/login.jsx
  src/routes/private-routes.jsx
  src/routes/sections.jsx
  src/sections/forgot-password/apiForgotPassword.js
  src/sections/forgot-password/forgot-password-view.jsx
  src/sections/forgot-password/index.js
  src/sections/forgot-password/useForgotPassword.js
  src/sections/login/login-view.jsx
  src/sections/login/useGetUser.js
  src/sections/login/useIsAuthenticated.js
  src/sections/login/useLogin.js
Labels: documentation, enhancement

#23 Add Google OAuth in login
  package.json
  src/app.jsx
  src/layouts/dashboard/nav.jsx
  src/routes/sections.jsx
  src/sections/login/login-view.jsx
  src/sections/login/oauth-callback.jsx
  src/sections/overview/view/app-view.jsx
Labels: documentation, enhancement

#24 Fixing esling config file and fixing error
  .eslintrc
  .prettierrc
  jsconfig.json
  src/sections/login/apiAuth.js
  src/sections/login/oauth-callback.jsx
  src/utils/authUtils.js
Labels: bug

#29 Feature landing page
  package.json
  public/assets/landing-assets/WavyLines.png
  public/assets/landing-assets/avatar.png
  public/assets/landing-assets/blob-1.svg
  public/assets/landing-assets/blob-2.svg
  public/assets/landing-assets/cta.png
  public/assets/landing-assets/feature-chat.png
  public/assets/landing-assets/feature-mentoring.png
  public/assets/landing-assets/grey-star.svg
  public/assets/landing-assets/hero-1.png
  public/assets/landing-assets/hero-2.png
  public/assets/landing-assets/hero-3.png
  public/assets/landing-assets/icon-group.png
  public/assets/landing-assets/icon-idea.png
  public/assets/landing-assets/icon-one-to-one.png
  public/assets/landing-assets/index.js
  public/assets/landing-assets/lock.svg
  public/assets/landing-assets/logo.svg
  public/assets/landing-assets/quotationMark.png
  public/assets/landing-assets/react.svg
  public/assets/landing-assets/ttt-logo.png
  public/assets/landing-assets/ttt_element_1.png
  public/assets/landing-assets/ttt_element_2.png
  public/assets/landing-assets/wave-haikei.svg
  public/assets/landing-assets/yellow-star.svg
  src/_mock/Courses.js
  src/_mock/features.js
  src/app.css
  src/app.jsx
  src/components/ui/infinite-moving-cards.jsx
  src/global.css
  src/landing-page/categories.jsx
  src/landing-page/category-card.jsx
  src/landing-page/cta.jsx
  src/landing-page/feature-card.jsx
  src/landing-page/features.jsx
  src/landing-page/footer.jsx
  src/landing-page/hero.jsx
  src/landing-page/index.js
  src/landing-page/navbar.jsx
  src/landing-page/offers.jsx
  src/landing-page/testimonials.jsx
  src/pages/landing-home.jsx
  src/routes/sections.jsx
  tailwind.config.js
Labels: documentation, enhancement

#26 Add TEMP spinner in loading state and Error boundry
  .prettierrc
  package.json
  public/assets/loading-spinner.gif
  src/components/ui/error-fallback.jsx
  src/components/ui/spinner.jsx
  src/components/ui/system-down.jsx
  src/layouts/dashboard/nav.jsx
  src/main.jsx
  src/routes/private-routes.jsx
  src/routes/sections.jsx
  src/sections/login/oauth-callback.jsx
Labels: documentation, enhancement

#25 Feature news feed and support chat
  package.json
  src/app.jsx
  src/components/logo/logo.jsx
  src/components/support-chat/apiSalesforce.js
  src/components/support-chat/index.js
  src/components/support-chat/support-chat.jsx
  src/components/support-chat/useAccessToken.js
  src/components/support-chat/useSubmitEnquiry.js
  src/sections/forgot-password/forgot-password-view.jsx
  src/sections/overview/view/apiFeeds.js
  src/sections/overview/view/app-view.jsx
  src/sections/overview/view/useFeeds.js
Labels: documentation, enhancement

#36 Updating Rooms
  package.json
  src/_mock/products.js
  src/components/room-categories/index.jsx
  src/global.css
  src/main.jsx
  src/pages/assessment.jsx
  src/pages/create-rooms.jsx
  src/pages/room.jsx
  src/routes/sections.jsx
  src/sections/overview/view/app-view.jsx
  src/sections/products/view/products-view.jsx
  src/sections/rooms/explore-rooms.jsx
  src/sections/rooms/view/apiRooms.jsx
  src/sections/rooms/view/useRooms.jsx
  src/theme/typography.js
Labels: documentation, enhancement

#37 add skeleton for loading state in news update section
  src/sections/overview/app-news-update.jsx
  src/sections/overview/view/app-view.jsx
Labels: documentation
